# NeON build file (http://github.com/c4s4/neon)

default: [clean, articles]
extends:
- c4s4/build/golang.yml
- c4s4/build/release.yml

properties:
  SWEETOHM: '../sweetohm/content/article'
  GO_VERSIONS:
  - 1.0.3
  - 1.1.2
  - 1.2.2
  - 1.3.3
  - 1.4.3
  - 1.5.4
  - 1.6.4
  - 1.7.6
  - 1.8.7
  - 1.9.4
  - 1.10rc1

targets:

  articles:
    doc: Generate articles
    steps:
    - mkdir: "#{BUILD_DIR}"
    - $: 'go run gointerfaces.go #{join(GO_VERSIONS, " ")} > #{BUILD_DIR}/interfaces.md'
    - copy:  'go-interfaces*.md'
      todir: '#{BUILD_DIR}'
    - read: '#{BUILD_DIR}/interfaces.md'
      to:   'interfaces'
    - for:  'file'
      in:   'find(BUILD_DIR, "go-interfaces*.md")'
      do:
      - replace: '#{BUILD_DIR}/#{file}'
        with:
          'INTERFACES': '#{interfaces}'
          'UPDATE':     '#{now()[0:10]}'
    - copy:  'go-interfaces*.md'
      dir:   =BUILD_DIR
      todir: =SWEETOHM
