# NeON build file (http://github.com/c4s4/neon)

extends: golang
default: [clean, check, articles]
configuration: '~/.neon/github.yml'

properties:
  SWEETOHM: '../sweetohm/content/article'
  GO_VERSIONS:
  - '1.16'
  - '1.15.8'
  - '1.14.15'
  - '1.13.15'
  - '1.12.17'
  - '1.11.13'
  - '1.10.8'
  - '1.9.7'
  - '1.8.7'
  - '1.7.6'
  - '1.6.4'
  - '1.5.4'
  - '1.4.3'
  - '1.3.3'
  - '1.2.2'
  - '1.1.2'
  - '1.0.3'

targets:

  articles:
    doc: Generate articles
    steps:
    - mkdir: "#{BUILD_DIR}"
    - $: ['go', 'run', 'gointerfaces.go']
      +: GO_VERSIONS
      1>: '={BUILD_DIR}/interfaces.md'
      1x: true
    - copy:  'go-interfaces*.md'
      todir: '={BUILD_DIR}'
    - read: '={BUILD_DIR}/interfaces.md'
      to:   'interfaces'
    - for:  'file'
      in:   'find(BUILD_DIR, "go-interfaces*.md")'
      do:
      - replace: '#{BUILD_DIR}/#{file}'
        with:
          'INTERFACES': =interfaces
          'UPDATE':     '={now()[0:10]}'
    - copy:  'go-interfaces*.md'
      dir:   =BUILD_DIR
      todir: =SWEETOHM
