name:    gointerfaces
doc:     Build gointerfaces project
default: test

properties:
  NAME:      "gointerfaces"
  VERSION:   '#{run("changelog", "release", "version")}'
  BUILD_DIR: "build"
  ARC_DIR:   "#{BUILD_DIR}/#{NAME}-#{VERSION}"
  DEPENDENCIES: []
  GO_VERSION:
  - 1.0.3
  - 1.1.2
  - 1.2.2
  - 1.3.3
  - 1.4.3
  - 1.5.4
  - 1.6.4
  - 1.7.5
  - 1.8rc3

targets:

  deps:
    doc: Install Go dependencies
    steps:
    - for: dependency
      in:  DEPENDENCIES
      do:
      - print: "Getting dependency #{dependency}..."
      - 'go get "#{dependency}"'

  test:
    doc: Run Go tests
    steps:
    - 'go test'

  build:
    doc: Build Go application
    steps:
    - mkdir: "#{BUILD_DIR}"
    - 'go build -o #{BUILD_DIR}/#{NAME}'

  archive:
    doc: Build distribution archive
    steps:
    - mkdir: "#{BUILD_DIR}/#{NAME}-#{VERSION}/bin/"
    - 'gox -output=#{ARC_DIR}/bin/{{.Dir}}_{{.OS}}_{{.Arch}}'
    - copy:
      - "LICENSE.txt"
      - "CHANGELOG.yml"
      todir: "#{ARC_DIR}"
    - 'md2pdf -o #{ARC_DIR}/README.pdf README.md'
    - tar: "**/*"
      dir: "#{ARC_DIR}"
      prefix: "#{NAME}-#{VERSION}"
      to: "#{BUILD_DIR}/#{NAME}-#{VERSION}.tar.gz"

  release:
    doc: Make a release
    depends: [clean, test, archive]
    steps:
    - 'release'

#  articles:
#    doc: Generate articles
#    steps:
#    - mkdir: "#{BUILD_DIR}"
#	- 'go run gointerfaces.go $(GO_VERSION) > $(BUILD_DIR)/interfaces.md
#	cp go-interfaces*.md $(BUILD_DIR)
#	sed -i -e "/INTERFACES/{r $(BUILD_DIR)/interfaces.md" -e "d}" $(BUILD_DIR)/go-interfaces.md
#	sed -i -e "/INTERFACES/{r $(BUILD_DIR)/interfaces.md" -e "d}" $(BUILD_DIR)/go-interfaces.en.md
#	sed -i -e "s/UPDATE/$(shell date -I)/g" $(BUILD_DIR)/go-interfaces.md
#	sed -i -e "s/UPDATE/$(shell date -I)/g" $(BUILD_DIR)/go-interfaces.en.md

  clean:
    doc: Clean generated files
    steps:
    - delete: "#{BUILD_DIR}"

